var ec2 = require("ec2");

exports.generateAMI = function(instanceId, name, callback) {
    // Create an instance of the AmazonEC2Client.
    var client = ec2.createClient(
        { key:      process.env["AWS_ACCESS_KEY_ID"]
        , secret:   process.env["AWS_SECRET_ACCESS_KEY"]
    });
    
    var newImageId;
    
    console.log('About to create image from ' + instanceId + ' with name ' + name);
    
    client.call("CreateImage", {
        InstanceId: instanceId,
        Description: "autogenerated " + name,
        Name: name
    }, function(response) {
        newImageId = response.imageId;
        //now terminate the instance...
        client.call("TerminateInstances", {
            InstanceId: instanceId
        }, function(response) {
            //all done
        });
    });
    
    // When all of the Amazon Query API calls and polls complete, we know that our
    // Amazon EC2 instance is ready for use.
    client.on("end", function () {
       console.log("Created a new AMI with id: " + newImageId);
       callback(null, newImageId);
    });
    
    // Run the trasaction described above.
    client.execute();
};